### ISSUE TITLE
How to write test for floating-point properties to avoid infinite loop?

### ISSUE THREAD

**Issue by rpietruc** [grogers0/CppQuickCheck#7]
If I write following test:
struct PropertyInfiniteLoop : cppqc::Property\<float\> {
    bool check(const float &a) const override { return (a > 0); }
};
and call:
cppqc::quickCheckOutput(PropertyInfiniteLoop());
It will enter an infinite loop.
Is it expected behavior?
How can I avoid this issue properly?

**Comment by grogers0** [comment]
Seems like it is stuck trying to shrink the test case but generating too many cases. My guess is that it does iteratively improve the shrink each time (it moves towards 0), but because there are a LOT of floating point values between a reasonable first guess and 0, it never actually finishes shrinking.

Maybe a good workaround here is to stop after a certain number of tries.

**Comment by grogers0** [comment]
590b886e7880dd10861e81172fc04617d0d2100a

I believe this fixes the problem (at least for floats specfically). There are a couple other things we could do to fix it more generally (like bounding the number of shrinks or bailing if we try to shrink to the same value)

**Comment by rpietruc** [comment]
Thank you, That works form me.
